font-family = "Geist Mono"
mouse-shift-capture = true
quit-after-last-window-closed = true
confirm-close-surface = false

# vbrajon's syntax colors
background = #000000
foreground = #FFFFFF
cursor-color = #ffdd00
cursor-text = #000000
selection-background = #333333
selection-foreground = #ffffff
palette = 0=#000000
palette = 1=#ff6677
palette = 2=#aaee44
palette = 3=#ffdd00
palette = 4=#66bbff
palette = 5=#ff99ff
palette = 6=#77eeff
palette = 7=#ffffff
palette = 8=#555555
palette = 9=#ff3344
palette = 10=#77dd00
palette = 11=#ffaa33
palette = 12=#3399ff
palette = 13=#ff66ee
palette = 14=#33ddff
palette = 15=#aaaaaa
