bind -n F12 resize-pane -Z
bind | split-window -h
bind - split-window -v
bind + new-window

set -g status-keys vi
set -g mode-keys vi

set -g mouse on
unbind -n MouseDown3Pane
bind -n DoubleClick1Pane resize-pane -Z
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel pbcopy

set -g extended-keys on
set -g extended-keys-format csi-u

set -g base-index 1
set -g pane-base-index 1

set -s escape-time 0
set -g history-limit 100000

# Powerline
set -g status-bg "#000000"
set -g status-fg "#FFFFFF"
set -g status-left-length 60
set -g status-right-length 90
set -g status-interval 1
set -g status-left "#[fg=#FFFFFF,bg=#333333,bold] #S #[fg=#333333,bg=#000000]"
set -g status-right "#[fg=#333333,bg=#000000]#[fg=#FFFFFF,bg=#333333] %H:%M #[fg=#555555,bg=#333333]#[fg=#FFFFFF,bg=#555555] %d-%b-%y #[fg=#777777,bg=#555555]#[fg=#FFFFFF,bg=#777777,bold] #h "
set -g window-status-format "#[fg=#666666,bg=#000000] #P:#W "
set -g window-status-current-format "#[fg=#000000,bg=#FFFFFF]#[fg=#000000,bg=#FFFFFF,bold] #P:#W #[fg=#FFFFFF,bg=#000000]"
set -g pane-border-style "fg=#333333"
set -g pane-active-border-style "fg=#FFFFFF"
set -g pane-border-status off
set -g message-style "fg=#FFFFFF,bg=#333333,bold"
